services:
  nginx:
    image: nginx:latest@sha256:5a88c9c45479443d7be2eadc894b4ed0a9801bae03d97a5760ae13b5c2005942
    ports:
      - 8080:80/tcp

  alloy:
    image: grafana/alloy:${GRAFANA_ALLOY_VERSION:-v1.17.1}
    ports:
      - 12345:12345
    env_file:
      - ../.env
    environment:
      GC_DESTINATIONS_FILE: /etc/alloy/cloud/destinations.alloy
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - ../_cloud/destinations.alloy:/etc/alloy/cloud/destinations.alloy
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - nginx
