services:
  mysql:
    image: mysql:9.7@sha256:8fdf311514c91fa5014e93e98e19d7f5d9eb162a462c13100c956dacc278ee21
    environment:
      - MYSQL_ROOT_PASSWORD=alloy
      - MYSQL_DATABASE=alloy
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-palloy"]
      interval: 10s
      timeout: 5s
      retries: 5

  alloy:
    image: grafana/alloy:${GRAFANA_ALLOY_VERSION:-v1.17.1}
    ports:
      - 12345:12345
    env_file:
      - ../.env
    environment:
      GC_DESTINATIONS_FILE: /etc/alloy/cloud/destinations.alloy
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - ../_cloud/destinations.alloy:/etc/alloy/cloud/destinations.alloy
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      mysql:
        condition: service_healthy
