---
cluster:
  name: alloy-scenarios-cloud

destinations:
  tempo:
    type: otlp
    urlFrom: sys.env("GC_OTLP_URL")
    protocol: http
    auth:
      type: basic
      usernameFrom: sys.env("GC_OTLP_USER")
      passwordFrom: sys.env("GC_TOKEN")
    metrics:
      enabled: false
    logs:
      enabled: false
    traces:
      enabled: true

applicationObservability:
  enabled: true
  collector: alloy-receiver
  receivers:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true
  metrics:
    enabled: false
  logs:
    enabled: false

collectors:
  alloy-receiver:
    presets: [deployment]
    extraEnvFrom:
      - secretRef:
          name: grafana-cloud
