---
cluster:
  name: alloy-scenarios-cloud

destinations:
  prometheus:
    type: prometheus
    urlFrom: sys.env("GC_PROM_URL")
    auth:
      type: basic
      usernameFrom: sys.env("GC_PROM_USER")
      passwordFrom: sys.env("GC_TOKEN")

clusterMetrics:
  enabled: true

annotationAutodiscovery:
  enabled: true
  collector: alloy-metrics

collectors:
  alloy-metrics:
    presets: [clustered, statefulset]
    extraEnvFrom:
      - secretRef:
          name: grafana-cloud

telemetryServices:
  kube-state-metrics:
    deploy: true
