version: '3.8'

services:
  # Syslog simulator using a Python script
  logs-file:
    image: python:${PYTHON_VERSION:-3.11-slim}
    container_name: logs-file
    volumes:
      - ./main.py:/main.py  # Syslog simulator script
      - ./logs:/logs  # Directory to store the logs
    depends_on:
      - alloy
    command: ["python3", "/main.py"]
  

  alloy:
    image: grafana/alloy:${GRAFANA_ALLOY_VERSION:-v1.17.1}
    env_file:
      - ../.env
    environment:
      GC_DESTINATIONS_FILE: /etc/alloy/cloud/destinations.alloy
    ports:
      - 12345:12345
      - 4318:4318
    volumes:
      - ../_cloud/destinations.alloy:/etc/alloy/cloud/destinations.alloy
      - ./config.alloy:/etc/alloy/config.alloy
      - ./logs:/temp/logs
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy

