services:
  snmpd:
    build:
      context: ./snmpd
      dockerfile: Dockerfile
      args:
        - DEBIAN_VERSION=${DEBIAN_VERSION:-bookworm-slim}

  alloy:
    image: grafana/alloy:${GRAFANA_ALLOY_VERSION:-v1.17.1}
    depends_on:
      - snmpd
    ports:
      - 12345:12345
    env_file:
      - ../.env
    environment:
      GC_DESTINATIONS_FILE: /etc/alloy/cloud/destinations.alloy
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - ../_cloud/destinations.alloy:/etc/alloy/cloud/destinations.alloy
      - ./snmp.yml:/etc/alloy/snmp.yml
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
