services:
  alloy:
    image: grafana/alloy:${GRAFANA_ALLOY_VERSION:-v1.17.1}
    privileged: true
    ports:
      - 12345:12345
    env_file:
      - ../.env
    environment:
      ALLOY_DEPLOY_MODE: docker
      GC_DESTINATIONS_FILE: /etc/alloy/cloud/destinations.alloy
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - ../_cloud/destinations.alloy:/etc/alloy/cloud/destinations.alloy
      - /proc:/rootproc:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys:ro
      - /:/rootfs:ro
      - /dev/disk/:/dev/disk:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    devices:
      - /dev/kmsg
