version: '3.8'

services:
  alloy:
    image: grafana/alloy:${GRAFANA_ALLOY_VERSION:-v1.17.1}
    env_file:
      - ../.env
    environment:
      GC_DESTINATIONS_FILE: /etc/alloy/cloud/destinations.alloy
    ports:
      - 8888:8888
      - 12345:12345     # Alloy UI
    volumes:
      - ../_cloud/destinations.alloy:/etc/alloy/cloud/destinations.alloy
      - ./config-otel.yaml:/etc/alloy/config-otel.yaml
      - ./config.alloy:/etc/alloy/config.alloy
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      - /:/hostfs:ro
    environment:
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_ETC=/hostfs/etc
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
    pid: host
    command: otel --config=/etc/alloy/config-otel.yaml

  stress:
    image: polinux/stress@sha256:b6144f84f9c15dac80deb48d3a646b55c7043ab1d83ea0a697c09097aaad21aa
    command: ["stress", "--cpu", "1", "--vm", "1", "--vm-bytes", "64M"]

