version: '3.8'

services:
    image: grafana/tempo:${GRAFANA_TEMPO_VERSION:-2.10.7}
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      - 3201:3200
    volumes:

  alloy:
    image: grafana/alloy:${GRAFANA_ALLOY_VERSION:-v1.17.1}
    env_file:
      - ../.env
    environment:
      GC_DESTINATIONS_FILE: /etc/alloy/cloud/destinations.alloy
    ports:
      - 8888:8888
      - 4317:4317
      - 4318:4318
      - 12345:12345     # Alloy UI
    volumes:
      - ../_cloud/destinations.alloy:/etc/alloy/cloud/destinations.alloy
      - ./config-otel.yaml:/etc/alloy/config-otel.yaml
      - ./config.alloy:/etc/alloy/config.alloy
    command: otel --config=/etc/alloy/config-otel.yaml

  demo-app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=${PYTHON_VERSION:-3.11-slim}
    ports:
      - 8080:8080
    depends_on:
      - alloy

