version: '3.8'

services:
  alloy:
    image: grafana/alloy:${GRAFANA_ALLOY_VERSION:-v1.17.1}
    env_file:
      - ../.env
    environment:
      GC_DESTINATIONS_FILE: /etc/alloy/cloud/destinations.alloy
    ports:
      - 8888:8888
      - 4317:4317/tcp
      - 4318:4318/tcp
      - 12345:12345     # Alloy UI
    volumes:
      - ../_cloud/destinations.alloy:/etc/alloy/cloud/destinations.alloy
      - ./config-otel.yaml:/etc/alloy/config-otel.yaml
      - ./config.alloy:/etc/alloy/config.alloy
    command: otel --config=/etc/alloy/config-otel.yaml

  demo-app:
    build:
      context: ./app
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.11-slim}
    depends_on:
      - alloy

