---
cluster:
  name: alloy-scenarios-cloud

destinations:
  pyroscope:
    type: pyroscope
    urlFrom: sys.env("GC_PYRO_URL")
    auth:
      type: basic
      usernameFrom: sys.env("GC_PYRO_USER")
      passwordFrom: sys.env("GC_TOKEN")

profiling:
  enabled: true
  collector: alloy-profiles
  pprof:
    enabled: true

collectors:
  alloy-profiles:
    presets: [privileged, daemonset]
    extraEnvFrom:
      - secretRef:
          name: grafana-cloud
