version: '3.8'

services:

  # Syslog simulator using a Python script
  simulator:
    image: python:${PYTHON_VERSION:-3.11-slim}
    container_name: simulator
    volumes:
      - ./simulator.py:/simulator.py  # Syslog simulator script
    environment:
      - TARGET_HOST=alloy
      - TARGET_PORT=9999
    command: ["python3", "/simulator.py"]
    depends_on:
      - alloy
  

  alloy:
    image: grafana/alloy:${GRAFANA_ALLOY_VERSION:-v1.17.1}
    env_file:
      - ../.env
    environment:
      GC_DESTINATIONS_FILE: /etc/alloy/cloud/destinations.alloy
    ports:
      - 12345:12345
      - 4318:4318
    volumes:
      - ../_cloud/destinations.alloy:/etc/alloy/cloud/destinations.alloy
      - ./config.alloy:/etc/alloy/config.alloy
      - ./logs:/tmp/app-logs/
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy

volumes:
  rsyslog_data:
