version: '3.8'

services:
  mail-house-01:
    image: python:${PYTHON_VERSION:-3.11-slim}
    volumes:
      - ./main.py:/main.py
    depends_on:
      - alloy
    command: ["python3", "/main.py"]
    environment:
      - MAIL_HOUSE_ID=DEPOT-01
    restart: unless-stopped
  
  mail-house-02:
    image: python:${PYTHON_VERSION:-3.11-slim}
    volumes:
      - ./main.py:/main.py
    depends_on:
      - alloy
    command: ["python3", "/main.py"]
    environment:
      - MAIL_HOUSE_ID=DEPOT-02
    restart: unless-stopped
    
  mail-house-03:
    image: python:${PYTHON_VERSION:-3.11-slim}
    volumes:
      - ./main.py:/main.py
    depends_on:
      - alloy
    command: ["python3", "/main.py"]
    environment:
      - MAIL_HOUSE_ID=DEPOT-03
    restart: unless-stopped

  alloy:
    image: grafana/alloy:${GRAFANA_ALLOY_VERSION:-v1.17.1}
    env_file:
      - ../.env
    environment:
      GC_DESTINATIONS_FILE: /etc/alloy/cloud/destinations.alloy
    ports:
      - 12345:12345
      - 4318:4318
    volumes:
      - ../_cloud/destinations.alloy:/etc/alloy/cloud/destinations.alloy
      - ./config.alloy:/etc/alloy/config.alloy
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy

